[[profile]]
name = "docked-ultrawide"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    match = "eDP-2"
    enable = true
    mode = { width = 3840, height = 2160, refresh = 60}
    position = { x = 0, y = 0 }
    scale = 2.0 

    [[profile.output]]
    match = "DP-3"
    enable = true
    mode = { width = 5120, height = 1440, refresh = 60}
    position = { x = 1920, y = 0 }
    scale = 1.3

[[profile]]
name = "laptop"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    match = "eDP-2"
    enable = true
    mode = { width = 3840, height = 2160, refresh = 60}
    position = { x = 0, y = 0 }
    scale = 2.0 
